CREATE TABLE BOOKE
(
    BOOKMAKER_ID INT NOT NULL,
    COTE_ID INT NOT NULL,
    CONSTRAINT BOOKE_PK PRIMARY KEY (BOOKMAKER_ID, COTE_ID),
    CONSTRAINT BOOKE_BOOKMAKERS_ID_FK FOREIGN KEY (BOOKMAKER_ID) REFERENCES BOOKMAKERS (ID),
    CONSTRAINT BOOKE_COTE_ID_FK FOREIGN KEY (COTE_ID) REFERENCES COTE (ID)
);
CREATE TABLE BOOKMAKERS
(
    ID INT PRIMARY KEY NOT NULL,
    NOM_BOOKMAKERS VARCHAR(25)
);
CREATE TABLE COTE
(
    ID INT PRIMARY KEY NOT NULL,
    SCORE_COTE VARCHAR(25),
    VICTOIRE_COTE VARCHAR(25),
    DEFAITE_COTE VARCHAR(25),
    NB_BUT_COTE INT
);
CREATE TABLE "MATCH"
(
    ID INT PRIMARY KEY NOT NULL,
    NOM_MATCH VARCHAR(25),
    LIEU_MATCH VARCHAR(25),
    DATE DATE,
    DUREE INT
);
CREATE TABLE PARI
(
    MATCH_ID INT NOT NULL,
    COTE_ID INT NOT NULL,
    CONSTRAINT PARI_PK PRIMARY KEY (MATCH_ID, COTE_ID),
    CONSTRAINT PARI_MATCH_ID_FK FOREIGN KEY (MATCH_ID) REFERENCES "MATCH" (ID),
    CONSTRAINT PARI_COTE_ID_FK FOREIGN KEY (COTE_ID) REFERENCES COTE (ID)
);
CREATE TABLE PARIEUR
(
    ID INT PRIMARY KEY NOT NULL,
    NOM_PARIEUR VARCHAR(25),
    LIMCOINS_PARIEUR INT DEFAULT 1000
);
CREATE TABLE PARTICIPANTS
(
    ID INT PRIMARY KEY NOT NULL,
    NOM_PARTICIPANTS VARCHAR(25)
);
CREATE TABLE PARTICIPE
(
    MATCH_ID INT NOT NULL,
    PARTICIPANTS_ID INT NOT NULL,
    CONSTRAINT PARTICIPE_MATCH_ID_PARTICIPANTS_ID_PK PRIMARY KEY (MATCH_ID, PARTICIPANTS_ID),
    CONSTRAINT PARTICIPE_MATCH_ID_FK FOREIGN KEY (MATCH_ID) REFERENCES "MATCH" (ID),
    CONSTRAINT PARTICIPE_PARTICIPANTS_ID_FK FOREIGN KEY (PARTICIPANTS_ID) REFERENCES PARTICIPANTS (ID)
);
CREATE TABLE UTILISATEUR
(
    ID INT PRIMARY KEY NOT NULL,
    NOM_UTILISATEUR VARCHAR(25),
    MDP_UTILISATEUR VARCHAR(25),
    TYPE_UTILISATEUR VARCHAR(25)
);